/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as BookingRouteImport } from './routes/booking'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as PublicIndexRouteImport } from './routes/_public/index'
import { Route as ProviderVerificationRouteImport } from './routes/provider/verification'
import { Route as ProviderOnboardingRouteImport } from './routes/provider/onboarding'
import { Route as ProfileUserIdRouteImport } from './routes/profile/$userId'
import { Route as PublicVerifyEmailRouteImport } from './routes/_public/verify-email'
import { Route as PublicTermsRouteImport } from './routes/_public/terms'
import { Route as PublicSigninRouteImport } from './routes/_public/signin'
import { Route as PublicServicesRouteImport } from './routes/_public/services'
import { Route as PublicResetPasswordRouteImport } from './routes/_public/reset-password'
import { Route as PublicProviderSignupRouteImport } from './routes/_public/provider-signup'
import { Route as PublicPrivacyRouteImport } from './routes/_public/privacy'
import { Route as PublicHowItWorksRouteImport } from './routes/_public/how-it-works'
import { Route as PublicForgotPasswordRouteImport } from './routes/_public/forgot-password'
import { Route as PublicClientSignupRouteImport } from './routes/_public/client-signup'
import { Route as PublicAboutRouteImport } from './routes/_public/about'
import { Route as DashboardProviderRouteRouteImport } from './routes/dashboard/provider/route'
import { Route as DashboardClientRouteRouteImport } from './routes/dashboard/client/route'
import { Route as DashboardAdminRouteRouteImport } from './routes/dashboard/admin/route'
import { Route as DashboardProviderIndexRouteImport } from './routes/dashboard/provider/index'
import { Route as DashboardClientIndexRouteImport } from './routes/dashboard/client/index'
import { Route as DashboardAdminIndexRouteImport } from './routes/dashboard/admin/index'
import { Route as PublicProvidersIndexRouteImport } from './routes/_public/providers/index'
import { Route as DashboardProviderWalletRouteImport } from './routes/dashboard/provider/wallet'
import { Route as DashboardProviderSettingsRouteImport } from './routes/dashboard/provider/settings'
import { Route as DashboardProviderReviewsRouteImport } from './routes/dashboard/provider/reviews'
import { Route as DashboardProviderRequestsRouteImport } from './routes/dashboard/provider/requests'
import { Route as DashboardProviderOverviewRouteImport } from './routes/dashboard/provider/overview'
import { Route as DashboardProviderNotificationsRouteImport } from './routes/dashboard/provider/notifications'
import { Route as DashboardProviderMessagesRouteImport } from './routes/dashboard/provider/messages'
import { Route as DashboardProviderJobsRouteImport } from './routes/dashboard/provider/jobs'
import { Route as DashboardProviderJobBoardRouteImport } from './routes/dashboard/provider/job-board'
import { Route as DashboardProviderCalendarRouteImport } from './routes/dashboard/provider/calendar'
import { Route as DashboardClientWalletRouteImport } from './routes/dashboard/client/wallet'
import { Route as DashboardClientSettingsRouteImport } from './routes/dashboard/client/settings'
import { Route as DashboardClientReviewsRouteImport } from './routes/dashboard/client/reviews'
import { Route as DashboardClientPostJobRouteImport } from './routes/dashboard/client/post-job'
import { Route as DashboardClientOverviewRouteImport } from './routes/dashboard/client/overview'
import { Route as DashboardClientNotificationsRouteImport } from './routes/dashboard/client/notifications'
import { Route as DashboardClientMyJobsRouteImport } from './routes/dashboard/client/my-jobs'
import { Route as DashboardClientMessagesRouteImport } from './routes/dashboard/client/messages'
import { Route as DashboardClientBrowseRouteImport } from './routes/dashboard/client/browse'
import { Route as DashboardClientBookingsRouteImport } from './routes/dashboard/client/bookings'
import { Route as DashboardClientBookingRouteImport } from './routes/dashboard/client/booking'
import { Route as DashboardAdminVerificationRouteImport } from './routes/dashboard/admin/verification'
import { Route as DashboardAdminUsersRouteImport } from './routes/dashboard/admin/users'
import { Route as DashboardAdminServicesRouteImport } from './routes/dashboard/admin/services'
import { Route as DashboardAdminRevenueRouteImport } from './routes/dashboard/admin/revenue'
import { Route as DashboardAdminOverviewRouteImport } from './routes/dashboard/admin/overview'
import { Route as DashboardAdminJobsRouteImport } from './routes/dashboard/admin/jobs'
import { Route as DashboardAdminDisputesRouteImport } from './routes/dashboard/admin/disputes'
import { Route as DashboardAdminCountriesRouteImport } from './routes/dashboard/admin/countries'
import { Route as PublicProvidersProviderIdRouteImport } from './routes/_public/providers/$providerId'
import { Route as DashboardProviderProfileIndexRouteImport } from './routes/dashboard/provider/profile/index'
import { Route as DashboardClientProvidersIndexRouteImport } from './routes/dashboard/client/providers/index'
import { Route as DashboardClientProfileIndexRouteImport } from './routes/dashboard/client/profile/index'
import { Route as DashboardProviderProfileUserIdRouteImport } from './routes/dashboard/provider/profile/$userId'
import { Route as DashboardProviderJobJobIdRouteImport } from './routes/dashboard/provider/job/$jobId'
import { Route as DashboardClientProvidersProfileRouteImport } from './routes/dashboard/client/providers/profile'
import { Route as DashboardClientProfileUserIdRouteImport } from './routes/dashboard/client/profile/$userId'
import { Route as DashboardClientJobJobIdRouteImport } from './routes/dashboard/client/job/$jobId'

const BookingRoute = BookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicIndexRoute = PublicIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PublicRoute,
} as any)
const ProviderVerificationRoute = ProviderVerificationRouteImport.update({
  id: '/provider/verification',
  path: '/provider/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderOnboardingRoute = ProviderOnboardingRouteImport.update({
  id: '/provider/onboarding',
  path: '/provider/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUserIdRoute = ProfileUserIdRouteImport.update({
  id: '/profile/$userId',
  path: '/profile/$userId',
  getParentRoute: () => rootRouteImport,
} as any)
const PublicVerifyEmailRoute = PublicVerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => PublicRoute,
} as any)
const PublicTermsRoute = PublicTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => PublicRoute,
} as any)
const PublicSigninRoute = PublicSigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => PublicRoute,
} as any)
const PublicServicesRoute = PublicServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => PublicRoute,
} as any)
const PublicResetPasswordRoute = PublicResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => PublicRoute,
} as any)
const PublicProviderSignupRoute = PublicProviderSignupRouteImport.update({
  id: '/provider-signup',
  path: '/provider-signup',
  getParentRoute: () => PublicRoute,
} as any)
const PublicPrivacyRoute = PublicPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => PublicRoute,
} as any)
const PublicHowItWorksRoute = PublicHowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => PublicRoute,
} as any)
const PublicForgotPasswordRoute = PublicForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => PublicRoute,
} as any)
const PublicClientSignupRoute = PublicClientSignupRouteImport.update({
  id: '/client-signup',
  path: '/client-signup',
  getParentRoute: () => PublicRoute,
} as any)
const PublicAboutRoute = PublicAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => PublicRoute,
} as any)
const DashboardProviderRouteRoute = DashboardProviderRouteRouteImport.update({
  id: '/dashboard/provider',
  path: '/dashboard/provider',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardClientRouteRoute = DashboardClientRouteRouteImport.update({
  id: '/dashboard/client',
  path: '/dashboard/client',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminRouteRoute = DashboardAdminRouteRouteImport.update({
  id: '/dashboard/admin',
  path: '/dashboard/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProviderIndexRoute = DashboardProviderIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardProviderRouteRoute,
} as any)
const DashboardClientIndexRoute = DashboardClientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardClientRouteRoute,
} as any)
const DashboardAdminIndexRoute = DashboardAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardAdminRouteRoute,
} as any)
const PublicProvidersIndexRoute = PublicProvidersIndexRouteImport.update({
  id: '/providers/',
  path: '/providers/',
  getParentRoute: () => PublicRoute,
} as any)
const DashboardProviderWalletRoute = DashboardProviderWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => DashboardProviderRouteRoute,
} as any)
const DashboardProviderSettingsRoute =
  DashboardProviderSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => DashboardProviderRouteRoute,
  } as any)
const DashboardProviderReviewsRoute =
  DashboardProviderReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => DashboardProviderRouteRoute,
  } as any)
const DashboardProviderRequestsRoute =
  DashboardProviderRequestsRouteImport.update({
    id: '/requests',
    path: '/requests',
    getParentRoute: () => DashboardProviderRouteRoute,
  } as any)
const DashboardProviderOverviewRoute =
  DashboardProviderOverviewRouteImport.update({
    id: '/overview',
    path: '/overview',
    getParentRoute: () => DashboardProviderRouteRoute,
  } as any)
const DashboardProviderNotificationsRoute =
  DashboardProviderNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => DashboardProviderRouteRoute,
  } as any)
const DashboardProviderMessagesRoute =
  DashboardProviderMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => DashboardProviderRouteRoute,
  } as any)
const DashboardProviderJobsRoute = DashboardProviderJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => DashboardProviderRouteRoute,
} as any)
const DashboardProviderJobBoardRoute =
  DashboardProviderJobBoardRouteImport.update({
    id: '/job-board',
    path: '/job-board',
    getParentRoute: () => DashboardProviderRouteRoute,
  } as any)
const DashboardProviderCalendarRoute =
  DashboardProviderCalendarRouteImport.update({
    id: '/calendar',
    path: '/calendar',
    getParentRoute: () => DashboardProviderRouteRoute,
  } as any)
const DashboardClientWalletRoute = DashboardClientWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => DashboardClientRouteRoute,
} as any)
const DashboardClientSettingsRoute = DashboardClientSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardClientRouteRoute,
} as any)
const DashboardClientReviewsRoute = DashboardClientReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => DashboardClientRouteRoute,
} as any)
const DashboardClientPostJobRoute = DashboardClientPostJobRouteImport.update({
  id: '/post-job',
  path: '/post-job',
  getParentRoute: () => DashboardClientRouteRoute,
} as any)
const DashboardClientOverviewRoute = DashboardClientOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => DashboardClientRouteRoute,
} as any)
const DashboardClientNotificationsRoute =
  DashboardClientNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => DashboardClientRouteRoute,
  } as any)
const DashboardClientMyJobsRoute = DashboardClientMyJobsRouteImport.update({
  id: '/my-jobs',
  path: '/my-jobs',
  getParentRoute: () => DashboardClientRouteRoute,
} as any)
const DashboardClientMessagesRoute = DashboardClientMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => DashboardClientRouteRoute,
} as any)
const DashboardClientBrowseRoute = DashboardClientBrowseRouteImport.update({
  id: '/browse',
  path: '/browse',
  getParentRoute: () => DashboardClientRouteRoute,
} as any)
const DashboardClientBookingsRoute = DashboardClientBookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => DashboardClientRouteRoute,
} as any)
const DashboardClientBookingRoute = DashboardClientBookingRouteImport.update({
  id: '/booking',
  path: '/booking',
  getParentRoute: () => DashboardClientRouteRoute,
} as any)
const DashboardAdminVerificationRoute =
  DashboardAdminVerificationRouteImport.update({
    id: '/verification',
    path: '/verification',
    getParentRoute: () => DashboardAdminRouteRoute,
  } as any)
const DashboardAdminUsersRoute = DashboardAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardAdminRouteRoute,
} as any)
const DashboardAdminServicesRoute = DashboardAdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => DashboardAdminRouteRoute,
} as any)
const DashboardAdminRevenueRoute = DashboardAdminRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => DashboardAdminRouteRoute,
} as any)
const DashboardAdminOverviewRoute = DashboardAdminOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => DashboardAdminRouteRoute,
} as any)
const DashboardAdminJobsRoute = DashboardAdminJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => DashboardAdminRouteRoute,
} as any)
const DashboardAdminDisputesRoute = DashboardAdminDisputesRouteImport.update({
  id: '/disputes',
  path: '/disputes',
  getParentRoute: () => DashboardAdminRouteRoute,
} as any)
const DashboardAdminCountriesRoute = DashboardAdminCountriesRouteImport.update({
  id: '/countries',
  path: '/countries',
  getParentRoute: () => DashboardAdminRouteRoute,
} as any)
const PublicProvidersProviderIdRoute =
  PublicProvidersProviderIdRouteImport.update({
    id: '/providers/$providerId',
    path: '/providers/$providerId',
    getParentRoute: () => PublicRoute,
  } as any)
const DashboardProviderProfileIndexRoute =
  DashboardProviderProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => DashboardProviderRouteRoute,
  } as any)
const DashboardClientProvidersIndexRoute =
  DashboardClientProvidersIndexRouteImport.update({
    id: '/providers/',
    path: '/providers/',
    getParentRoute: () => DashboardClientRouteRoute,
  } as any)
const DashboardClientProfileIndexRoute =
  DashboardClientProfileIndexRouteImport.update({
    id: '/profile/',
    path: '/profile/',
    getParentRoute: () => DashboardClientRouteRoute,
  } as any)
const DashboardProviderProfileUserIdRoute =
  DashboardProviderProfileUserIdRouteImport.update({
    id: '/profile/$userId',
    path: '/profile/$userId',
    getParentRoute: () => DashboardProviderRouteRoute,
  } as any)
const DashboardProviderJobJobIdRoute =
  DashboardProviderJobJobIdRouteImport.update({
    id: '/job/$jobId',
    path: '/job/$jobId',
    getParentRoute: () => DashboardProviderRouteRoute,
  } as any)
const DashboardClientProvidersProfileRoute =
  DashboardClientProvidersProfileRouteImport.update({
    id: '/providers/profile',
    path: '/providers/profile',
    getParentRoute: () => DashboardClientRouteRoute,
  } as any)
const DashboardClientProfileUserIdRoute =
  DashboardClientProfileUserIdRouteImport.update({
    id: '/profile/$userId',
    path: '/profile/$userId',
    getParentRoute: () => DashboardClientRouteRoute,
  } as any)
const DashboardClientJobJobIdRoute = DashboardClientJobJobIdRouteImport.update({
  id: '/job/$jobId',
  path: '/job/$jobId',
  getParentRoute: () => DashboardClientRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof PublicIndexRoute
  '/booking': typeof BookingRoute
  '/dashboard/admin': typeof DashboardAdminRouteRouteWithChildren
  '/dashboard/client': typeof DashboardClientRouteRouteWithChildren
  '/dashboard/provider': typeof DashboardProviderRouteRouteWithChildren
  '/about': typeof PublicAboutRoute
  '/client-signup': typeof PublicClientSignupRoute
  '/forgot-password': typeof PublicForgotPasswordRoute
  '/how-it-works': typeof PublicHowItWorksRoute
  '/privacy': typeof PublicPrivacyRoute
  '/provider-signup': typeof PublicProviderSignupRoute
  '/reset-password': typeof PublicResetPasswordRoute
  '/services': typeof PublicServicesRoute
  '/signin': typeof PublicSigninRoute
  '/terms': typeof PublicTermsRoute
  '/verify-email': typeof PublicVerifyEmailRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/provider/onboarding': typeof ProviderOnboardingRoute
  '/provider/verification': typeof ProviderVerificationRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/providers/$providerId': typeof PublicProvidersProviderIdRoute
  '/dashboard/admin/countries': typeof DashboardAdminCountriesRoute
  '/dashboard/admin/disputes': typeof DashboardAdminDisputesRoute
  '/dashboard/admin/jobs': typeof DashboardAdminJobsRoute
  '/dashboard/admin/overview': typeof DashboardAdminOverviewRoute
  '/dashboard/admin/revenue': typeof DashboardAdminRevenueRoute
  '/dashboard/admin/services': typeof DashboardAdminServicesRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/admin/verification': typeof DashboardAdminVerificationRoute
  '/dashboard/client/booking': typeof DashboardClientBookingRoute
  '/dashboard/client/bookings': typeof DashboardClientBookingsRoute
  '/dashboard/client/browse': typeof DashboardClientBrowseRoute
  '/dashboard/client/messages': typeof DashboardClientMessagesRoute
  '/dashboard/client/my-jobs': typeof DashboardClientMyJobsRoute
  '/dashboard/client/notifications': typeof DashboardClientNotificationsRoute
  '/dashboard/client/overview': typeof DashboardClientOverviewRoute
  '/dashboard/client/post-job': typeof DashboardClientPostJobRoute
  '/dashboard/client/reviews': typeof DashboardClientReviewsRoute
  '/dashboard/client/settings': typeof DashboardClientSettingsRoute
  '/dashboard/client/wallet': typeof DashboardClientWalletRoute
  '/dashboard/provider/calendar': typeof DashboardProviderCalendarRoute
  '/dashboard/provider/job-board': typeof DashboardProviderJobBoardRoute
  '/dashboard/provider/jobs': typeof DashboardProviderJobsRoute
  '/dashboard/provider/messages': typeof DashboardProviderMessagesRoute
  '/dashboard/provider/notifications': typeof DashboardProviderNotificationsRoute
  '/dashboard/provider/overview': typeof DashboardProviderOverviewRoute
  '/dashboard/provider/requests': typeof DashboardProviderRequestsRoute
  '/dashboard/provider/reviews': typeof DashboardProviderReviewsRoute
  '/dashboard/provider/settings': typeof DashboardProviderSettingsRoute
  '/dashboard/provider/wallet': typeof DashboardProviderWalletRoute
  '/providers/': typeof PublicProvidersIndexRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/client/': typeof DashboardClientIndexRoute
  '/dashboard/provider/': typeof DashboardProviderIndexRoute
  '/dashboard/client/job/$jobId': typeof DashboardClientJobJobIdRoute
  '/dashboard/client/profile/$userId': typeof DashboardClientProfileUserIdRoute
  '/dashboard/client/providers/profile': typeof DashboardClientProvidersProfileRoute
  '/dashboard/provider/job/$jobId': typeof DashboardProviderJobJobIdRoute
  '/dashboard/provider/profile/$userId': typeof DashboardProviderProfileUserIdRoute
  '/dashboard/client/profile/': typeof DashboardClientProfileIndexRoute
  '/dashboard/client/providers/': typeof DashboardClientProvidersIndexRoute
  '/dashboard/provider/profile/': typeof DashboardProviderProfileIndexRoute
}
export interface FileRoutesByTo {
  '/booking': typeof BookingRoute
  '/about': typeof PublicAboutRoute
  '/client-signup': typeof PublicClientSignupRoute
  '/forgot-password': typeof PublicForgotPasswordRoute
  '/how-it-works': typeof PublicHowItWorksRoute
  '/privacy': typeof PublicPrivacyRoute
  '/provider-signup': typeof PublicProviderSignupRoute
  '/reset-password': typeof PublicResetPasswordRoute
  '/services': typeof PublicServicesRoute
  '/signin': typeof PublicSigninRoute
  '/terms': typeof PublicTermsRoute
  '/verify-email': typeof PublicVerifyEmailRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/provider/onboarding': typeof ProviderOnboardingRoute
  '/provider/verification': typeof ProviderVerificationRoute
  '/': typeof PublicIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/providers/$providerId': typeof PublicProvidersProviderIdRoute
  '/dashboard/admin/countries': typeof DashboardAdminCountriesRoute
  '/dashboard/admin/disputes': typeof DashboardAdminDisputesRoute
  '/dashboard/admin/jobs': typeof DashboardAdminJobsRoute
  '/dashboard/admin/overview': typeof DashboardAdminOverviewRoute
  '/dashboard/admin/revenue': typeof DashboardAdminRevenueRoute
  '/dashboard/admin/services': typeof DashboardAdminServicesRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/admin/verification': typeof DashboardAdminVerificationRoute
  '/dashboard/client/booking': typeof DashboardClientBookingRoute
  '/dashboard/client/bookings': typeof DashboardClientBookingsRoute
  '/dashboard/client/browse': typeof DashboardClientBrowseRoute
  '/dashboard/client/messages': typeof DashboardClientMessagesRoute
  '/dashboard/client/my-jobs': typeof DashboardClientMyJobsRoute
  '/dashboard/client/notifications': typeof DashboardClientNotificationsRoute
  '/dashboard/client/overview': typeof DashboardClientOverviewRoute
  '/dashboard/client/post-job': typeof DashboardClientPostJobRoute
  '/dashboard/client/reviews': typeof DashboardClientReviewsRoute
  '/dashboard/client/settings': typeof DashboardClientSettingsRoute
  '/dashboard/client/wallet': typeof DashboardClientWalletRoute
  '/dashboard/provider/calendar': typeof DashboardProviderCalendarRoute
  '/dashboard/provider/job-board': typeof DashboardProviderJobBoardRoute
  '/dashboard/provider/jobs': typeof DashboardProviderJobsRoute
  '/dashboard/provider/messages': typeof DashboardProviderMessagesRoute
  '/dashboard/provider/notifications': typeof DashboardProviderNotificationsRoute
  '/dashboard/provider/overview': typeof DashboardProviderOverviewRoute
  '/dashboard/provider/requests': typeof DashboardProviderRequestsRoute
  '/dashboard/provider/reviews': typeof DashboardProviderReviewsRoute
  '/dashboard/provider/settings': typeof DashboardProviderSettingsRoute
  '/dashboard/provider/wallet': typeof DashboardProviderWalletRoute
  '/providers': typeof PublicProvidersIndexRoute
  '/dashboard/admin': typeof DashboardAdminIndexRoute
  '/dashboard/client': typeof DashboardClientIndexRoute
  '/dashboard/provider': typeof DashboardProviderIndexRoute
  '/dashboard/client/job/$jobId': typeof DashboardClientJobJobIdRoute
  '/dashboard/client/profile/$userId': typeof DashboardClientProfileUserIdRoute
  '/dashboard/client/providers/profile': typeof DashboardClientProvidersProfileRoute
  '/dashboard/provider/job/$jobId': typeof DashboardProviderJobJobIdRoute
  '/dashboard/provider/profile/$userId': typeof DashboardProviderProfileUserIdRoute
  '/dashboard/client/profile': typeof DashboardClientProfileIndexRoute
  '/dashboard/client/providers': typeof DashboardClientProvidersIndexRoute
  '/dashboard/provider/profile': typeof DashboardProviderProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_public': typeof PublicRouteWithChildren
  '/booking': typeof BookingRoute
  '/dashboard/admin': typeof DashboardAdminRouteRouteWithChildren
  '/dashboard/client': typeof DashboardClientRouteRouteWithChildren
  '/dashboard/provider': typeof DashboardProviderRouteRouteWithChildren
  '/_public/about': typeof PublicAboutRoute
  '/_public/client-signup': typeof PublicClientSignupRoute
  '/_public/forgot-password': typeof PublicForgotPasswordRoute
  '/_public/how-it-works': typeof PublicHowItWorksRoute
  '/_public/privacy': typeof PublicPrivacyRoute
  '/_public/provider-signup': typeof PublicProviderSignupRoute
  '/_public/reset-password': typeof PublicResetPasswordRoute
  '/_public/services': typeof PublicServicesRoute
  '/_public/signin': typeof PublicSigninRoute
  '/_public/terms': typeof PublicTermsRoute
  '/_public/verify-email': typeof PublicVerifyEmailRoute
  '/profile/$userId': typeof ProfileUserIdRoute
  '/provider/onboarding': typeof ProviderOnboardingRoute
  '/provider/verification': typeof ProviderVerificationRoute
  '/_public/': typeof PublicIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/_public/providers/$providerId': typeof PublicProvidersProviderIdRoute
  '/dashboard/admin/countries': typeof DashboardAdminCountriesRoute
  '/dashboard/admin/disputes': typeof DashboardAdminDisputesRoute
  '/dashboard/admin/jobs': typeof DashboardAdminJobsRoute
  '/dashboard/admin/overview': typeof DashboardAdminOverviewRoute
  '/dashboard/admin/revenue': typeof DashboardAdminRevenueRoute
  '/dashboard/admin/services': typeof DashboardAdminServicesRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/admin/verification': typeof DashboardAdminVerificationRoute
  '/dashboard/client/booking': typeof DashboardClientBookingRoute
  '/dashboard/client/bookings': typeof DashboardClientBookingsRoute
  '/dashboard/client/browse': typeof DashboardClientBrowseRoute
  '/dashboard/client/messages': typeof DashboardClientMessagesRoute
  '/dashboard/client/my-jobs': typeof DashboardClientMyJobsRoute
  '/dashboard/client/notifications': typeof DashboardClientNotificationsRoute
  '/dashboard/client/overview': typeof DashboardClientOverviewRoute
  '/dashboard/client/post-job': typeof DashboardClientPostJobRoute
  '/dashboard/client/reviews': typeof DashboardClientReviewsRoute
  '/dashboard/client/settings': typeof DashboardClientSettingsRoute
  '/dashboard/client/wallet': typeof DashboardClientWalletRoute
  '/dashboard/provider/calendar': typeof DashboardProviderCalendarRoute
  '/dashboard/provider/job-board': typeof DashboardProviderJobBoardRoute
  '/dashboard/provider/jobs': typeof DashboardProviderJobsRoute
  '/dashboard/provider/messages': typeof DashboardProviderMessagesRoute
  '/dashboard/provider/notifications': typeof DashboardProviderNotificationsRoute
  '/dashboard/provider/overview': typeof DashboardProviderOverviewRoute
  '/dashboard/provider/requests': typeof DashboardProviderRequestsRoute
  '/dashboard/provider/reviews': typeof DashboardProviderReviewsRoute
  '/dashboard/provider/settings': typeof DashboardProviderSettingsRoute
  '/dashboard/provider/wallet': typeof DashboardProviderWalletRoute
  '/_public/providers/': typeof PublicProvidersIndexRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/client/': typeof DashboardClientIndexRoute
  '/dashboard/provider/': typeof DashboardProviderIndexRoute
  '/dashboard/client/job/$jobId': typeof DashboardClientJobJobIdRoute
  '/dashboard/client/profile/$userId': typeof DashboardClientProfileUserIdRoute
  '/dashboard/client/providers/profile': typeof DashboardClientProvidersProfileRoute
  '/dashboard/provider/job/$jobId': typeof DashboardProviderJobJobIdRoute
  '/dashboard/provider/profile/$userId': typeof DashboardProviderProfileUserIdRoute
  '/dashboard/client/profile/': typeof DashboardClientProfileIndexRoute
  '/dashboard/client/providers/': typeof DashboardClientProvidersIndexRoute
  '/dashboard/provider/profile/': typeof DashboardProviderProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/booking'
    | '/dashboard/admin'
    | '/dashboard/client'
    | '/dashboard/provider'
    | '/about'
    | '/client-signup'
    | '/forgot-password'
    | '/how-it-works'
    | '/privacy'
    | '/provider-signup'
    | '/reset-password'
    | '/services'
    | '/signin'
    | '/terms'
    | '/verify-email'
    | '/profile/$userId'
    | '/provider/onboarding'
    | '/provider/verification'
    | '/dashboard/'
    | '/providers/$providerId'
    | '/dashboard/admin/countries'
    | '/dashboard/admin/disputes'
    | '/dashboard/admin/jobs'
    | '/dashboard/admin/overview'
    | '/dashboard/admin/revenue'
    | '/dashboard/admin/services'
    | '/dashboard/admin/users'
    | '/dashboard/admin/verification'
    | '/dashboard/client/booking'
    | '/dashboard/client/bookings'
    | '/dashboard/client/browse'
    | '/dashboard/client/messages'
    | '/dashboard/client/my-jobs'
    | '/dashboard/client/notifications'
    | '/dashboard/client/overview'
    | '/dashboard/client/post-job'
    | '/dashboard/client/reviews'
    | '/dashboard/client/settings'
    | '/dashboard/client/wallet'
    | '/dashboard/provider/calendar'
    | '/dashboard/provider/job-board'
    | '/dashboard/provider/jobs'
    | '/dashboard/provider/messages'
    | '/dashboard/provider/notifications'
    | '/dashboard/provider/overview'
    | '/dashboard/provider/requests'
    | '/dashboard/provider/reviews'
    | '/dashboard/provider/settings'
    | '/dashboard/provider/wallet'
    | '/providers/'
    | '/dashboard/admin/'
    | '/dashboard/client/'
    | '/dashboard/provider/'
    | '/dashboard/client/job/$jobId'
    | '/dashboard/client/profile/$userId'
    | '/dashboard/client/providers/profile'
    | '/dashboard/provider/job/$jobId'
    | '/dashboard/provider/profile/$userId'
    | '/dashboard/client/profile/'
    | '/dashboard/client/providers/'
    | '/dashboard/provider/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/booking'
    | '/about'
    | '/client-signup'
    | '/forgot-password'
    | '/how-it-works'
    | '/privacy'
    | '/provider-signup'
    | '/reset-password'
    | '/services'
    | '/signin'
    | '/terms'
    | '/verify-email'
    | '/profile/$userId'
    | '/provider/onboarding'
    | '/provider/verification'
    | '/'
    | '/dashboard'
    | '/providers/$providerId'
    | '/dashboard/admin/countries'
    | '/dashboard/admin/disputes'
    | '/dashboard/admin/jobs'
    | '/dashboard/admin/overview'
    | '/dashboard/admin/revenue'
    | '/dashboard/admin/services'
    | '/dashboard/admin/users'
    | '/dashboard/admin/verification'
    | '/dashboard/client/booking'
    | '/dashboard/client/bookings'
    | '/dashboard/client/browse'
    | '/dashboard/client/messages'
    | '/dashboard/client/my-jobs'
    | '/dashboard/client/notifications'
    | '/dashboard/client/overview'
    | '/dashboard/client/post-job'
    | '/dashboard/client/reviews'
    | '/dashboard/client/settings'
    | '/dashboard/client/wallet'
    | '/dashboard/provider/calendar'
    | '/dashboard/provider/job-board'
    | '/dashboard/provider/jobs'
    | '/dashboard/provider/messages'
    | '/dashboard/provider/notifications'
    | '/dashboard/provider/overview'
    | '/dashboard/provider/requests'
    | '/dashboard/provider/reviews'
    | '/dashboard/provider/settings'
    | '/dashboard/provider/wallet'
    | '/providers'
    | '/dashboard/admin'
    | '/dashboard/client'
    | '/dashboard/provider'
    | '/dashboard/client/job/$jobId'
    | '/dashboard/client/profile/$userId'
    | '/dashboard/client/providers/profile'
    | '/dashboard/provider/job/$jobId'
    | '/dashboard/provider/profile/$userId'
    | '/dashboard/client/profile'
    | '/dashboard/client/providers'
    | '/dashboard/provider/profile'
  id:
    | '__root__'
    | '/_public'
    | '/booking'
    | '/dashboard/admin'
    | '/dashboard/client'
    | '/dashboard/provider'
    | '/_public/about'
    | '/_public/client-signup'
    | '/_public/forgot-password'
    | '/_public/how-it-works'
    | '/_public/privacy'
    | '/_public/provider-signup'
    | '/_public/reset-password'
    | '/_public/services'
    | '/_public/signin'
    | '/_public/terms'
    | '/_public/verify-email'
    | '/profile/$userId'
    | '/provider/onboarding'
    | '/provider/verification'
    | '/_public/'
    | '/dashboard/'
    | '/_public/providers/$providerId'
    | '/dashboard/admin/countries'
    | '/dashboard/admin/disputes'
    | '/dashboard/admin/jobs'
    | '/dashboard/admin/overview'
    | '/dashboard/admin/revenue'
    | '/dashboard/admin/services'
    | '/dashboard/admin/users'
    | '/dashboard/admin/verification'
    | '/dashboard/client/booking'
    | '/dashboard/client/bookings'
    | '/dashboard/client/browse'
    | '/dashboard/client/messages'
    | '/dashboard/client/my-jobs'
    | '/dashboard/client/notifications'
    | '/dashboard/client/overview'
    | '/dashboard/client/post-job'
    | '/dashboard/client/reviews'
    | '/dashboard/client/settings'
    | '/dashboard/client/wallet'
    | '/dashboard/provider/calendar'
    | '/dashboard/provider/job-board'
    | '/dashboard/provider/jobs'
    | '/dashboard/provider/messages'
    | '/dashboard/provider/notifications'
    | '/dashboard/provider/overview'
    | '/dashboard/provider/requests'
    | '/dashboard/provider/reviews'
    | '/dashboard/provider/settings'
    | '/dashboard/provider/wallet'
    | '/_public/providers/'
    | '/dashboard/admin/'
    | '/dashboard/client/'
    | '/dashboard/provider/'
    | '/dashboard/client/job/$jobId'
    | '/dashboard/client/profile/$userId'
    | '/dashboard/client/providers/profile'
    | '/dashboard/provider/job/$jobId'
    | '/dashboard/provider/profile/$userId'
    | '/dashboard/client/profile/'
    | '/dashboard/client/providers/'
    | '/dashboard/provider/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  PublicRoute: typeof PublicRouteWithChildren
  BookingRoute: typeof BookingRoute
  DashboardAdminRouteRoute: typeof DashboardAdminRouteRouteWithChildren
  DashboardClientRouteRoute: typeof DashboardClientRouteRouteWithChildren
  DashboardProviderRouteRoute: typeof DashboardProviderRouteRouteWithChildren
  ProfileUserIdRoute: typeof ProfileUserIdRoute
  ProviderOnboardingRoute: typeof ProviderOnboardingRoute
  ProviderVerificationRoute: typeof ProviderVerificationRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/booking': {
      id: '/booking'
      path: '/booking'
      fullPath: '/booking'
      preLoaderRoute: typeof BookingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/': {
      id: '/_public/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof PublicIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/provider/verification': {
      id: '/provider/verification'
      path: '/provider/verification'
      fullPath: '/provider/verification'
      preLoaderRoute: typeof ProviderVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider/onboarding': {
      id: '/provider/onboarding'
      path: '/provider/onboarding'
      fullPath: '/provider/onboarding'
      preLoaderRoute: typeof ProviderOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$userId': {
      id: '/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/profile/$userId'
      preLoaderRoute: typeof ProfileUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_public/verify-email': {
      id: '/_public/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof PublicVerifyEmailRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/terms': {
      id: '/_public/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof PublicTermsRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/signin': {
      id: '/_public/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof PublicSigninRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/services': {
      id: '/_public/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof PublicServicesRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/reset-password': {
      id: '/_public/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof PublicResetPasswordRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/provider-signup': {
      id: '/_public/provider-signup'
      path: '/provider-signup'
      fullPath: '/provider-signup'
      preLoaderRoute: typeof PublicProviderSignupRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/privacy': {
      id: '/_public/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PublicPrivacyRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/how-it-works': {
      id: '/_public/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof PublicHowItWorksRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/forgot-password': {
      id: '/_public/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof PublicForgotPasswordRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/client-signup': {
      id: '/_public/client-signup'
      path: '/client-signup'
      fullPath: '/client-signup'
      preLoaderRoute: typeof PublicClientSignupRouteImport
      parentRoute: typeof PublicRoute
    }
    '/_public/about': {
      id: '/_public/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof PublicAboutRouteImport
      parentRoute: typeof PublicRoute
    }
    '/dashboard/provider': {
      id: '/dashboard/provider'
      path: '/dashboard/provider'
      fullPath: '/dashboard/provider'
      preLoaderRoute: typeof DashboardProviderRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/client': {
      id: '/dashboard/client'
      path: '/dashboard/client'
      fullPath: '/dashboard/client'
      preLoaderRoute: typeof DashboardClientRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/provider/': {
      id: '/dashboard/provider/'
      path: '/'
      fullPath: '/dashboard/provider/'
      preLoaderRoute: typeof DashboardProviderIndexRouteImport
      parentRoute: typeof DashboardProviderRouteRoute
    }
    '/dashboard/client/': {
      id: '/dashboard/client/'
      path: '/'
      fullPath: '/dashboard/client/'
      preLoaderRoute: typeof DashboardClientIndexRouteImport
      parentRoute: typeof DashboardClientRouteRoute
    }
    '/dashboard/admin/': {
      id: '/dashboard/admin/'
      path: '/'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof DashboardAdminIndexRouteImport
      parentRoute: typeof DashboardAdminRouteRoute
    }
    '/_public/providers/': {
      id: '/_public/providers/'
      path: '/providers'
      fullPath: '/providers/'
      preLoaderRoute: typeof PublicProvidersIndexRouteImport
      parentRoute: typeof PublicRoute
    }
    '/dashboard/provider/wallet': {
      id: '/dashboard/provider/wallet'
      path: '/wallet'
      fullPath: '/dashboard/provider/wallet'
      preLoaderRoute: typeof DashboardProviderWalletRouteImport
      parentRoute: typeof DashboardProviderRouteRoute
    }
    '/dashboard/provider/settings': {
      id: '/dashboard/provider/settings'
      path: '/settings'
      fullPath: '/dashboard/provider/settings'
      preLoaderRoute: typeof DashboardProviderSettingsRouteImport
      parentRoute: typeof DashboardProviderRouteRoute
    }
    '/dashboard/provider/reviews': {
      id: '/dashboard/provider/reviews'
      path: '/reviews'
      fullPath: '/dashboard/provider/reviews'
      preLoaderRoute: typeof DashboardProviderReviewsRouteImport
      parentRoute: typeof DashboardProviderRouteRoute
    }
    '/dashboard/provider/requests': {
      id: '/dashboard/provider/requests'
      path: '/requests'
      fullPath: '/dashboard/provider/requests'
      preLoaderRoute: typeof DashboardProviderRequestsRouteImport
      parentRoute: typeof DashboardProviderRouteRoute
    }
    '/dashboard/provider/overview': {
      id: '/dashboard/provider/overview'
      path: '/overview'
      fullPath: '/dashboard/provider/overview'
      preLoaderRoute: typeof DashboardProviderOverviewRouteImport
      parentRoute: typeof DashboardProviderRouteRoute
    }
    '/dashboard/provider/notifications': {
      id: '/dashboard/provider/notifications'
      path: '/notifications'
      fullPath: '/dashboard/provider/notifications'
      preLoaderRoute: typeof DashboardProviderNotificationsRouteImport
      parentRoute: typeof DashboardProviderRouteRoute
    }
    '/dashboard/provider/messages': {
      id: '/dashboard/provider/messages'
      path: '/messages'
      fullPath: '/dashboard/provider/messages'
      preLoaderRoute: typeof DashboardProviderMessagesRouteImport
      parentRoute: typeof DashboardProviderRouteRoute
    }
    '/dashboard/provider/jobs': {
      id: '/dashboard/provider/jobs'
      path: '/jobs'
      fullPath: '/dashboard/provider/jobs'
      preLoaderRoute: typeof DashboardProviderJobsRouteImport
      parentRoute: typeof DashboardProviderRouteRoute
    }
    '/dashboard/provider/job-board': {
      id: '/dashboard/provider/job-board'
      path: '/job-board'
      fullPath: '/dashboard/provider/job-board'
      preLoaderRoute: typeof DashboardProviderJobBoardRouteImport
      parentRoute: typeof DashboardProviderRouteRoute
    }
    '/dashboard/provider/calendar': {
      id: '/dashboard/provider/calendar'
      path: '/calendar'
      fullPath: '/dashboard/provider/calendar'
      preLoaderRoute: typeof DashboardProviderCalendarRouteImport
      parentRoute: typeof DashboardProviderRouteRoute
    }
    '/dashboard/client/wallet': {
      id: '/dashboard/client/wallet'
      path: '/wallet'
      fullPath: '/dashboard/client/wallet'
      preLoaderRoute: typeof DashboardClientWalletRouteImport
      parentRoute: typeof DashboardClientRouteRoute
    }
    '/dashboard/client/settings': {
      id: '/dashboard/client/settings'
      path: '/settings'
      fullPath: '/dashboard/client/settings'
      preLoaderRoute: typeof DashboardClientSettingsRouteImport
      parentRoute: typeof DashboardClientRouteRoute
    }
    '/dashboard/client/reviews': {
      id: '/dashboard/client/reviews'
      path: '/reviews'
      fullPath: '/dashboard/client/reviews'
      preLoaderRoute: typeof DashboardClientReviewsRouteImport
      parentRoute: typeof DashboardClientRouteRoute
    }
    '/dashboard/client/post-job': {
      id: '/dashboard/client/post-job'
      path: '/post-job'
      fullPath: '/dashboard/client/post-job'
      preLoaderRoute: typeof DashboardClientPostJobRouteImport
      parentRoute: typeof DashboardClientRouteRoute
    }
    '/dashboard/client/overview': {
      id: '/dashboard/client/overview'
      path: '/overview'
      fullPath: '/dashboard/client/overview'
      preLoaderRoute: typeof DashboardClientOverviewRouteImport
      parentRoute: typeof DashboardClientRouteRoute
    }
    '/dashboard/client/notifications': {
      id: '/dashboard/client/notifications'
      path: '/notifications'
      fullPath: '/dashboard/client/notifications'
      preLoaderRoute: typeof DashboardClientNotificationsRouteImport
      parentRoute: typeof DashboardClientRouteRoute
    }
    '/dashboard/client/my-jobs': {
      id: '/dashboard/client/my-jobs'
      path: '/my-jobs'
      fullPath: '/dashboard/client/my-jobs'
      preLoaderRoute: typeof DashboardClientMyJobsRouteImport
      parentRoute: typeof DashboardClientRouteRoute
    }
    '/dashboard/client/messages': {
      id: '/dashboard/client/messages'
      path: '/messages'
      fullPath: '/dashboard/client/messages'
      preLoaderRoute: typeof DashboardClientMessagesRouteImport
      parentRoute: typeof DashboardClientRouteRoute
    }
    '/dashboard/client/browse': {
      id: '/dashboard/client/browse'
      path: '/browse'
      fullPath: '/dashboard/client/browse'
      preLoaderRoute: typeof DashboardClientBrowseRouteImport
      parentRoute: typeof DashboardClientRouteRoute
    }
    '/dashboard/client/bookings': {
      id: '/dashboard/client/bookings'
      path: '/bookings'
      fullPath: '/dashboard/client/bookings'
      preLoaderRoute: typeof DashboardClientBookingsRouteImport
      parentRoute: typeof DashboardClientRouteRoute
    }
    '/dashboard/client/booking': {
      id: '/dashboard/client/booking'
      path: '/booking'
      fullPath: '/dashboard/client/booking'
      preLoaderRoute: typeof DashboardClientBookingRouteImport
      parentRoute: typeof DashboardClientRouteRoute
    }
    '/dashboard/admin/verification': {
      id: '/dashboard/admin/verification'
      path: '/verification'
      fullPath: '/dashboard/admin/verification'
      preLoaderRoute: typeof DashboardAdminVerificationRouteImport
      parentRoute: typeof DashboardAdminRouteRoute
    }
    '/dashboard/admin/users': {
      id: '/dashboard/admin/users'
      path: '/users'
      fullPath: '/dashboard/admin/users'
      preLoaderRoute: typeof DashboardAdminUsersRouteImport
      parentRoute: typeof DashboardAdminRouteRoute
    }
    '/dashboard/admin/services': {
      id: '/dashboard/admin/services'
      path: '/services'
      fullPath: '/dashboard/admin/services'
      preLoaderRoute: typeof DashboardAdminServicesRouteImport
      parentRoute: typeof DashboardAdminRouteRoute
    }
    '/dashboard/admin/revenue': {
      id: '/dashboard/admin/revenue'
      path: '/revenue'
      fullPath: '/dashboard/admin/revenue'
      preLoaderRoute: typeof DashboardAdminRevenueRouteImport
      parentRoute: typeof DashboardAdminRouteRoute
    }
    '/dashboard/admin/overview': {
      id: '/dashboard/admin/overview'
      path: '/overview'
      fullPath: '/dashboard/admin/overview'
      preLoaderRoute: typeof DashboardAdminOverviewRouteImport
      parentRoute: typeof DashboardAdminRouteRoute
    }
    '/dashboard/admin/jobs': {
      id: '/dashboard/admin/jobs'
      path: '/jobs'
      fullPath: '/dashboard/admin/jobs'
      preLoaderRoute: typeof DashboardAdminJobsRouteImport
      parentRoute: typeof DashboardAdminRouteRoute
    }
    '/dashboard/admin/disputes': {
      id: '/dashboard/admin/disputes'
      path: '/disputes'
      fullPath: '/dashboard/admin/disputes'
      preLoaderRoute: typeof DashboardAdminDisputesRouteImport
      parentRoute: typeof DashboardAdminRouteRoute
    }
    '/dashboard/admin/countries': {
      id: '/dashboard/admin/countries'
      path: '/countries'
      fullPath: '/dashboard/admin/countries'
      preLoaderRoute: typeof DashboardAdminCountriesRouteImport
      parentRoute: typeof DashboardAdminRouteRoute
    }
    '/_public/providers/$providerId': {
      id: '/_public/providers/$providerId'
      path: '/providers/$providerId'
      fullPath: '/providers/$providerId'
      preLoaderRoute: typeof PublicProvidersProviderIdRouteImport
      parentRoute: typeof PublicRoute
    }
    '/dashboard/provider/profile/': {
      id: '/dashboard/provider/profile/'
      path: '/profile'
      fullPath: '/dashboard/provider/profile/'
      preLoaderRoute: typeof DashboardProviderProfileIndexRouteImport
      parentRoute: typeof DashboardProviderRouteRoute
    }
    '/dashboard/client/providers/': {
      id: '/dashboard/client/providers/'
      path: '/providers'
      fullPath: '/dashboard/client/providers/'
      preLoaderRoute: typeof DashboardClientProvidersIndexRouteImport
      parentRoute: typeof DashboardClientRouteRoute
    }
    '/dashboard/client/profile/': {
      id: '/dashboard/client/profile/'
      path: '/profile'
      fullPath: '/dashboard/client/profile/'
      preLoaderRoute: typeof DashboardClientProfileIndexRouteImport
      parentRoute: typeof DashboardClientRouteRoute
    }
    '/dashboard/provider/profile/$userId': {
      id: '/dashboard/provider/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/dashboard/provider/profile/$userId'
      preLoaderRoute: typeof DashboardProviderProfileUserIdRouteImport
      parentRoute: typeof DashboardProviderRouteRoute
    }
    '/dashboard/provider/job/$jobId': {
      id: '/dashboard/provider/job/$jobId'
      path: '/job/$jobId'
      fullPath: '/dashboard/provider/job/$jobId'
      preLoaderRoute: typeof DashboardProviderJobJobIdRouteImport
      parentRoute: typeof DashboardProviderRouteRoute
    }
    '/dashboard/client/providers/profile': {
      id: '/dashboard/client/providers/profile'
      path: '/providers/profile'
      fullPath: '/dashboard/client/providers/profile'
      preLoaderRoute: typeof DashboardClientProvidersProfileRouteImport
      parentRoute: typeof DashboardClientRouteRoute
    }
    '/dashboard/client/profile/$userId': {
      id: '/dashboard/client/profile/$userId'
      path: '/profile/$userId'
      fullPath: '/dashboard/client/profile/$userId'
      preLoaderRoute: typeof DashboardClientProfileUserIdRouteImport
      parentRoute: typeof DashboardClientRouteRoute
    }
    '/dashboard/client/job/$jobId': {
      id: '/dashboard/client/job/$jobId'
      path: '/job/$jobId'
      fullPath: '/dashboard/client/job/$jobId'
      preLoaderRoute: typeof DashboardClientJobJobIdRouteImport
      parentRoute: typeof DashboardClientRouteRoute
    }
  }
}

interface PublicRouteChildren {
  PublicAboutRoute: typeof PublicAboutRoute
  PublicClientSignupRoute: typeof PublicClientSignupRoute
  PublicForgotPasswordRoute: typeof PublicForgotPasswordRoute
  PublicHowItWorksRoute: typeof PublicHowItWorksRoute
  PublicPrivacyRoute: typeof PublicPrivacyRoute
  PublicProviderSignupRoute: typeof PublicProviderSignupRoute
  PublicResetPasswordRoute: typeof PublicResetPasswordRoute
  PublicServicesRoute: typeof PublicServicesRoute
  PublicSigninRoute: typeof PublicSigninRoute
  PublicTermsRoute: typeof PublicTermsRoute
  PublicVerifyEmailRoute: typeof PublicVerifyEmailRoute
  PublicIndexRoute: typeof PublicIndexRoute
  PublicProvidersProviderIdRoute: typeof PublicProvidersProviderIdRoute
  PublicProvidersIndexRoute: typeof PublicProvidersIndexRoute
}

const PublicRouteChildren: PublicRouteChildren = {
  PublicAboutRoute: PublicAboutRoute,
  PublicClientSignupRoute: PublicClientSignupRoute,
  PublicForgotPasswordRoute: PublicForgotPasswordRoute,
  PublicHowItWorksRoute: PublicHowItWorksRoute,
  PublicPrivacyRoute: PublicPrivacyRoute,
  PublicProviderSignupRoute: PublicProviderSignupRoute,
  PublicResetPasswordRoute: PublicResetPasswordRoute,
  PublicServicesRoute: PublicServicesRoute,
  PublicSigninRoute: PublicSigninRoute,
  PublicTermsRoute: PublicTermsRoute,
  PublicVerifyEmailRoute: PublicVerifyEmailRoute,
  PublicIndexRoute: PublicIndexRoute,
  PublicProvidersProviderIdRoute: PublicProvidersProviderIdRoute,
  PublicProvidersIndexRoute: PublicProvidersIndexRoute,
}

const PublicRouteWithChildren =
  PublicRoute._addFileChildren(PublicRouteChildren)

interface DashboardAdminRouteRouteChildren {
  DashboardAdminCountriesRoute: typeof DashboardAdminCountriesRoute
  DashboardAdminDisputesRoute: typeof DashboardAdminDisputesRoute
  DashboardAdminJobsRoute: typeof DashboardAdminJobsRoute
  DashboardAdminOverviewRoute: typeof DashboardAdminOverviewRoute
  DashboardAdminRevenueRoute: typeof DashboardAdminRevenueRoute
  DashboardAdminServicesRoute: typeof DashboardAdminServicesRoute
  DashboardAdminUsersRoute: typeof DashboardAdminUsersRoute
  DashboardAdminVerificationRoute: typeof DashboardAdminVerificationRoute
  DashboardAdminIndexRoute: typeof DashboardAdminIndexRoute
}

const DashboardAdminRouteRouteChildren: DashboardAdminRouteRouteChildren = {
  DashboardAdminCountriesRoute: DashboardAdminCountriesRoute,
  DashboardAdminDisputesRoute: DashboardAdminDisputesRoute,
  DashboardAdminJobsRoute: DashboardAdminJobsRoute,
  DashboardAdminOverviewRoute: DashboardAdminOverviewRoute,
  DashboardAdminRevenueRoute: DashboardAdminRevenueRoute,
  DashboardAdminServicesRoute: DashboardAdminServicesRoute,
  DashboardAdminUsersRoute: DashboardAdminUsersRoute,
  DashboardAdminVerificationRoute: DashboardAdminVerificationRoute,
  DashboardAdminIndexRoute: DashboardAdminIndexRoute,
}

const DashboardAdminRouteRouteWithChildren =
  DashboardAdminRouteRoute._addFileChildren(DashboardAdminRouteRouteChildren)

interface DashboardClientRouteRouteChildren {
  DashboardClientBookingRoute: typeof DashboardClientBookingRoute
  DashboardClientBookingsRoute: typeof DashboardClientBookingsRoute
  DashboardClientBrowseRoute: typeof DashboardClientBrowseRoute
  DashboardClientMessagesRoute: typeof DashboardClientMessagesRoute
  DashboardClientMyJobsRoute: typeof DashboardClientMyJobsRoute
  DashboardClientNotificationsRoute: typeof DashboardClientNotificationsRoute
  DashboardClientOverviewRoute: typeof DashboardClientOverviewRoute
  DashboardClientPostJobRoute: typeof DashboardClientPostJobRoute
  DashboardClientReviewsRoute: typeof DashboardClientReviewsRoute
  DashboardClientSettingsRoute: typeof DashboardClientSettingsRoute
  DashboardClientWalletRoute: typeof DashboardClientWalletRoute
  DashboardClientIndexRoute: typeof DashboardClientIndexRoute
  DashboardClientJobJobIdRoute: typeof DashboardClientJobJobIdRoute
  DashboardClientProfileUserIdRoute: typeof DashboardClientProfileUserIdRoute
  DashboardClientProvidersProfileRoute: typeof DashboardClientProvidersProfileRoute
  DashboardClientProfileIndexRoute: typeof DashboardClientProfileIndexRoute
  DashboardClientProvidersIndexRoute: typeof DashboardClientProvidersIndexRoute
}

const DashboardClientRouteRouteChildren: DashboardClientRouteRouteChildren = {
  DashboardClientBookingRoute: DashboardClientBookingRoute,
  DashboardClientBookingsRoute: DashboardClientBookingsRoute,
  DashboardClientBrowseRoute: DashboardClientBrowseRoute,
  DashboardClientMessagesRoute: DashboardClientMessagesRoute,
  DashboardClientMyJobsRoute: DashboardClientMyJobsRoute,
  DashboardClientNotificationsRoute: DashboardClientNotificationsRoute,
  DashboardClientOverviewRoute: DashboardClientOverviewRoute,
  DashboardClientPostJobRoute: DashboardClientPostJobRoute,
  DashboardClientReviewsRoute: DashboardClientReviewsRoute,
  DashboardClientSettingsRoute: DashboardClientSettingsRoute,
  DashboardClientWalletRoute: DashboardClientWalletRoute,
  DashboardClientIndexRoute: DashboardClientIndexRoute,
  DashboardClientJobJobIdRoute: DashboardClientJobJobIdRoute,
  DashboardClientProfileUserIdRoute: DashboardClientProfileUserIdRoute,
  DashboardClientProvidersProfileRoute: DashboardClientProvidersProfileRoute,
  DashboardClientProfileIndexRoute: DashboardClientProfileIndexRoute,
  DashboardClientProvidersIndexRoute: DashboardClientProvidersIndexRoute,
}

const DashboardClientRouteRouteWithChildren =
  DashboardClientRouteRoute._addFileChildren(DashboardClientRouteRouteChildren)

interface DashboardProviderRouteRouteChildren {
  DashboardProviderCalendarRoute: typeof DashboardProviderCalendarRoute
  DashboardProviderJobBoardRoute: typeof DashboardProviderJobBoardRoute
  DashboardProviderJobsRoute: typeof DashboardProviderJobsRoute
  DashboardProviderMessagesRoute: typeof DashboardProviderMessagesRoute
  DashboardProviderNotificationsRoute: typeof DashboardProviderNotificationsRoute
  DashboardProviderOverviewRoute: typeof DashboardProviderOverviewRoute
  DashboardProviderRequestsRoute: typeof DashboardProviderRequestsRoute
  DashboardProviderReviewsRoute: typeof DashboardProviderReviewsRoute
  DashboardProviderSettingsRoute: typeof DashboardProviderSettingsRoute
  DashboardProviderWalletRoute: typeof DashboardProviderWalletRoute
  DashboardProviderIndexRoute: typeof DashboardProviderIndexRoute
  DashboardProviderJobJobIdRoute: typeof DashboardProviderJobJobIdRoute
  DashboardProviderProfileUserIdRoute: typeof DashboardProviderProfileUserIdRoute
  DashboardProviderProfileIndexRoute: typeof DashboardProviderProfileIndexRoute
}

const DashboardProviderRouteRouteChildren: DashboardProviderRouteRouteChildren =
  {
    DashboardProviderCalendarRoute: DashboardProviderCalendarRoute,
    DashboardProviderJobBoardRoute: DashboardProviderJobBoardRoute,
    DashboardProviderJobsRoute: DashboardProviderJobsRoute,
    DashboardProviderMessagesRoute: DashboardProviderMessagesRoute,
    DashboardProviderNotificationsRoute: DashboardProviderNotificationsRoute,
    DashboardProviderOverviewRoute: DashboardProviderOverviewRoute,
    DashboardProviderRequestsRoute: DashboardProviderRequestsRoute,
    DashboardProviderReviewsRoute: DashboardProviderReviewsRoute,
    DashboardProviderSettingsRoute: DashboardProviderSettingsRoute,
    DashboardProviderWalletRoute: DashboardProviderWalletRoute,
    DashboardProviderIndexRoute: DashboardProviderIndexRoute,
    DashboardProviderJobJobIdRoute: DashboardProviderJobJobIdRoute,
    DashboardProviderProfileUserIdRoute: DashboardProviderProfileUserIdRoute,
    DashboardProviderProfileIndexRoute: DashboardProviderProfileIndexRoute,
  }

const DashboardProviderRouteRouteWithChildren =
  DashboardProviderRouteRoute._addFileChildren(
    DashboardProviderRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  PublicRoute: PublicRouteWithChildren,
  BookingRoute: BookingRoute,
  DashboardAdminRouteRoute: DashboardAdminRouteRouteWithChildren,
  DashboardClientRouteRoute: DashboardClientRouteRouteWithChildren,
  DashboardProviderRouteRoute: DashboardProviderRouteRouteWithChildren,
  ProfileUserIdRoute: ProfileUserIdRoute,
  ProviderOnboardingRoute: ProviderOnboardingRoute,
  ProviderVerificationRoute: ProviderVerificationRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
